Repository Steve2955/md2apkg, pull requests merged in 2021-07, with the labels that each got.

#1 simple test and first contribution :)
  package.json
Labels: enhancement

#2 some basic testing
  package-lock.json
  package.json
  test/index.js
Labels: enhancement

#7 fix defaults
  index.js
Labels: bug

#10 unify card fronts
  index.js
  src/Card.js
  src/index.js
Labels: enhancement

#8 implement support for ignoring certain heading levels
  index.js
  src/Card.js
  src/index.js
  test/index.js
Labels: enhancement

#11 implement support for images
  src/Image.js
  src/index.js
Labels: enhancement

#12 Images test
  test/img/blob.png
  test/index.js
Labels: enhancement

#13 simple action for running tests
  .github/workflows/npm-test.yml
  README.md
Labels: enhancement

#16 implement support for latex
  index.js
  src/Card.js
  src/index.js
Labels: enhancement

#17 default to first heading as deck name
  index.js
  src/index.js
Labels: enhancement

#18 fix duplicate cards when importing into anki
  package-lock.json
  package.json
  src/index.js
Labels: bug

#19 Error handling
  src/index.js
  test/index.js
Labels: enhancement

#20 implement support for tags
  README.md
  src/Card.js
  src/index.js
Labels: enhancement

#22 add logging for tags
  src/index.js
Labels: enhancement

#23 Tag tests
  test/index.js
Labels: enhancement

#21 some css
  src/index.js
  src/style.css
Labels: enhancement

#24 add simple vscode debug config
  .vscode/launch.json
Labels: question

#27 implement ability to extend card fronts
  README.md
  src/Card.js
  src/index.js
  src/style.js
Labels: enhancement

#28 Syntax highlighting
  README.md
  index.js
  package-lock.json
  package.json
  src/Card.js
  src/index.js
  src/style.css
Labels: enhancement

#30 Don't try to convert LaTeX-Syntax within code blocks
  src/Card.js
  src/index.js
Labels: bug

#31 more visually appealing README
  README.md
Labels: documentation
